# python serv.py <PORTNUMBER>

import socket
import sys

# TODO: implement functions
def ftp_get(file_name):
    # downloads file <file name> from the server
    pass

def ftp_put(file_name):
    # uploads file <file name> to the server
    pass

def ftp_ls():
    # lists files on the server
    pass

# TODO: input validation / error handling wherever needed

if len(sys.argv) != 2:
    print("Usage: python serv.py <PORTNUMBER>")
    sys.exit()

serverPort = int(sys.argv[1])

# create sockets 
controlSocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
dataSocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# bind sockets, dataSocket will use ephemeral port generated by 
controlSocket.bind(('', serverPort))
# dataSocket.bind(('',0))

controlSocket.listen(1)

data = ""
tempBuff = ""

while 1:
    try: 
        print("Waiting for a connection...")
        clientSock, addr = controlSocket.accept()
        print("Accepted connection")
        
        while len(data) < 40:
            tempBuff = clientSock.recv(40).decode()
            if not tempBuff:
                break
            data += tempBuff
    except:
        print("Could not connect")
        sys.exit()
        